---
- name: Configure filebeat download bs
  hosts: webservers
  remote_user: sysadmin
  become: true
  tasks:
      # Use command module
    - name: download the .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      # Use command module
    - name: install the .deb file
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

      # Copy file from ansible to correct folder
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml
        mode: '0755'

      # Use command module
    - name: enable metricbeat system
      command: metricbeat modules enable docker

      # Use command module
    - name: setup metricbeat
      command: metricbeat setup

      # Use command module
    - name: start metricbeat service
      command: service metricbeat start

      # Use systemd module
    - name: Enable filebeat service on boot
      systemd:
        name: metricbeat
        enabled: yes